### ISSUE TITLE
Proposed schema change: session

### ISSUE THREAD

**Issue by austenmc** [lotgd/crate-graphql#32]
Let's call it 'token' instead of apiKey. This is more consistent w/ the language most people would think of when talking about authentication.

**Comment by Vassyli** [comment]
I wanted to use a different name than token to make a clear distinction between symfony tokens and the api key.

**Comment by austenmc** [comment]
Im not sure that's a good idea from an API consumer's perspective. For example, as one of those consumers, I dont know what Symfony tokens are :). apiKey sounds like something you acquire as an application that accesses the API, not like an authentication mechanism.

**Comment by Vassyli** [comment]
Sure. How about keeping the name api key internally, but rename it for the api only? Or we might prefix it. sessionAuthenticationToken.
