### ISSUE TITLE
Let's change header structure for authorization

### ISSUE THREAD

**Issue by austenmc** [lotgd/crate-graphql#34]
Looks like we're using "token: <token>" for authorization?

We should switch to either an application specific header, like 'X-LotGD-Authentication: <token>' or override the oauth token one:

'Authentication: Bearer <token>'

Im not sure if this is ok honestly, since we're not using oauth, but I think it probably is.

**Comment by Vassyli** [comment]
This has nothing to do with oauth, but with the http standard. I don't know if oauth may be needing that header though.

**Comment by austenmc** [comment]
The Authentication: Bearer scheme was adopted as part of the oauth RFCs, but I agree we can just use it w/o caring about that.

**Comment by Vassyli** [comment]
Fixed with #37
